global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - '/etc/prometheus/prometheus_rules.yml'

scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 1s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'node'
    scrape_interval: 1s
    static_configs:
      - targets: ['node_exporter:9100']
        labels:
          group: 'production'
